# Do a full checkout, otherwise "git describe" fails.
git:
  depth: false
dist: xenial
language: go
# Repo name unfortunately does not match import path (case mismatch).
go_import_path: github.com/intel/pmem-csi
sudo: required
services:
  - docker
matrix:
  include:
  - go: 1.11.1
before_install:
  # Ubuntu Xenial doesn't have them yet and Travis CI doesn't support anything more recent. Ugly hack.
  - wget http://ftp.us.debian.org/debian/pool/main/n/ndctl/libndctl-dev_63-1.3_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/n/ndctl/libndctl6_63-1.3_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/n/ndctl/libdaxctl1_63-1.3_amd64.deb
  - sudo dpkg -i *.deb
before_script:
- mkdir -p bin
- wget https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-amd64 -O bin/dep
- chmod u+x bin/dep
- export PATH=$PWD/bin:$PATH
script:
# We don't need a Docker registry because TEST_CREATE_REGISTRY=true
# creates one inside the QEMU virtual cluster and directly copies
# the images into it.
- make -k build test build-images && TEST_CREATE_REGISTRY=true make test_e2e
