apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmem-csi-pvc-ext4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
  storageClassName: pmem-csi-sc-ext4 # defined in pmem-storageclass-ext4.yaml
