# Order of init containers from lvm-patch.yaml.
- op: add
  path: /spec/template/spec/initContainers/0/args/-
  value: -test.coverprofile=/var/lib/pmem-csi-coverage/pmem-ns-init.out
- op: add
  path: /spec/template/spec/initContainers/0/volumeMounts/-
  value:
    mountPath: /var/lib/pmem-csi-coverage
    name: coverage-dir
- op: add
  path: /spec/template/spec/initContainers/1/args/-
  value: -test.coverprofile=/var/lib/pmem-csi-coverage/pmem-vgm.out
- op: add
  path: /spec/template/spec/initContainers/1/volumeMounts
  value:
    - mountPath: /var/lib/pmem-csi-coverage
      name: coverage-dir
