apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pmem-csi-hook
webhooks:
  - name: pod-hook.pmem-csi.intel.com
    admissionReviewVersions:
    - v1beta1 # Depends on support in sigs.k8s.io/controller-runtime/pkg/webhook/admission
    sideEffects: None
    namespaceSelector:
      matchExpressions:
      - key: pmem-csi.intel.com/webhook
        operator: NotIn
        values: ["ignore"]
    objectSelector:
      matchExpressions:
      - key: pmem-csi.intel.com/webhook
        operator: NotIn
        values: ["ignore"]
    failurePolicy: Fail
    clientConfig:
      service:
        name: pmem-csi-scheduler
        namespace: default
        path: /pod/mutate
      caBundle:
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
