bases:
- ../kubernetes-base-lvm

resources:
- webhooks-rbac.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -mode=webhooks
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --schedulerListen=:8000
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -kube-api-qps=5.0
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -kube-api-burst=10
    - op: remove
      path: /spec/template/spec/containers/1
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: pmem-csi-node
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -mode=both
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -kube-api-qps=5.0
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -kube-api-burst=10

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: pmem-csi-controller
  spec:
    template:
      spec:
        # Simplify RBAC rules, add access to pods.
        serviceAccountName: pmem-csi-webhooks
# ... and instead add external-provisioner to each node.
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: pmem-csi-node
  spec:
    template:
      spec:
        serviceAccountName: pmem-csi-controller
        containers:
          - name: external-provisioner
            image: pohly/csi-provisioner:2020-12-01-6
            imagePullPolicy: IfNotPresent
            args:
            - -v=3
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --node-deployment
            - --node-deployment-base-delay=1s
            - --strict-topology=true
            - --immediate-topology=false
            - --timeout=5m
            - --default-fstype=ext4 # see https://github.com/kubernetes-csi/external-provisioner/issues/328#issuecomment-714801581
            # Basically never slow down client-side... only useful this way for scale testing.
            - --kube-api-qps=10000
            - --kube-api-burst=10000
            securityContext:
              readOnlyRootFilesystem: true
            volumeMounts:
            - name: socket-dir
              mountPath: /csi
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
