# Select LVM mode. The PMEM-CSI driver must be in container #0.
- op: add
  path: /spec/template/spec/containers/0/args/0
  value: "-deviceManager=lvm"

# LVM mode needs init containers.
- op: add
  path: /spec/template/spec/initContainers
  value:
  - name: pmem-ns-init
    imagePullPolicy: Always
    image: PMEM_REGISTRY/pmem-csi-driver:canary
    command: ["/go/bin/pmem-ns-init"]
    args: [ "-v=3", "-namespacesize=9" ]
    securityContext:
      privileged: true
    volumeMounts:
    - name: sys-dir
      mountPath: /sys
  - name: pmem-vgm
    imagePullPolicy: Always
    image: PMEM_REGISTRY/pmem-csi-driver:canary
    command: ["/go/bin/pmem-vgm"]
    args: [ "-v=3" ]
    securityContext:
      privileged: true

# /sys explicit mount added to get around read-only mount
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: sys-dir
    hostPath:
      path: /sys
      type: DirectoryOrCreate
