bases:
- ../kubernetes-base-lvm-coverage

resources:
- webhooks-rbac.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -mode=webhooks
    - op: remove
      path: /spec/template/spec/containers/1
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: pmem-csi-node
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: -mode=both

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: pmem-csi-controller
  spec:
    template:
      spec:
        # Simplify RBAC rules, add access to pods.
        serviceAccountName: pmem-csi-webhooks
# ... and instead add external-provisioner to each node, by building it into the PMEM-CSI driver binary.
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: pmem-csi-node
  spec:
    template:
      spec:
        serviceAccountName: pmem-csi-controller
        containers:
          - name: pmem-driver
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName

